site_name: grelmicro
site_description: grelmicro is a lightweight toolkit for building Python applications that need to coordinate work across processes, workers, or services.
site_url: https://grelinfo.github.io/grelmicro
theme:
  name: material
  palette:
    primary: green
    accent:  light green
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking

repo_name: grelinfo/grelmicro
repo_url: https://github.com/grelinfo/grelmicro

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- grelmicro: index.md
- User Guide:
    - cache.md
    - json.md
    - logging.md
    - tracing.md
    - resilience.md
    - sync.md
    - task.md
- API Reference:
    - reference/cache.md
    - reference/json.md
    - reference/logging.md
    - reference/resilience.md
    - reference/sync.md
    - reference/task.md
- Architecture:
    - architecture/index.md
    - architecture/backends.md
    - architecture/imports.md
    - architecture/sync.md
    - architecture/kubernetes.md
    - architecture/sqlite.md
    - architecture/tracing.md
- changelog.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_root_heading: false
            members_order: source
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: docs/snippets
