name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions: {}
env:
    UV_FROZEN: 1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
      - name: Install dependencies
        run: uv sync
      - name: Run Mypy
        run: mypy .

  test:
    name: Test Python ${{ matrix.python }}
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        python: ["3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: uv sync
      - name: Run Unit Tests
        run: pytest -x -m "not integration" --cov --junitxml=junit.xml -o junit_family=legacy
      - name: Upload Unit Test Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: "unit,py${{ matrix.python }}"
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload Unit Test Results to Codecov
        uses: codecov/test-results-action@v1
        with:
          flags: "unit,py${{ matrix.python }}"
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Run Integration Tests
        id: integration_tests
        run: pytest -x -m integration --cov --junitxml=junit.xml -o junit_family=legacy
      - name: Upload Integration Test Coverage to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ steps.integration_tests.outputs.exit_code != 0 }}
        with:
          flags: "integration,py${{ matrix.python }}"
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload Integration Test Results to Codecov
        uses: codecov/test-results-action@v1
        with:
          flags: "integration,py${ matrix.python }}"
          token: ${{ secrets.CODECOV_TOKEN }}